source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Piing' do

pod 'RESideMenu'
pod 'CardIO', '~> 5.0'
pod 'UICKeyChainStore', '~> 2.0'
pod 'Reachability'
pod 'Braintree', '~> 4.9.5'
pod 'GoogleMaps’, ‘~> 1.10.1’
pod 'Fabric'
pod 'Crashlytics'
pod 'SDWebImage', '~>3.8'
pod 'Firebase/Core'
pod 'Firebase/Crash'

end
